name: Release
on:
  push:
    branches: [ release ]
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Release
        uses: softprops/action-gh-release@v1
